# Generated by Django 4.1.5 on 2023-01-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreeksModels',
            new_name='GeeksModels',
        ),
    ]
